CREATE DATABASE contact_villa_db IF NOT EXISTS;

USE contact_villa_db;

CREATE TABLE subscribe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(200) NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE subscribe ( id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(200) NOT NULL, submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );
